from django.urls import path, include
from . import views
from .faculty import faculty

urlpatterns = [
    path('', views.home, name='home'),
    path('who-we-are/', views.who_we_are, name='who_we_are'),
    path('who-we-are/about-us/', views.about_us, name='about_us'),
    path('who-we-are/chancellor-message/', views.chancellor_message, name='chancellor_message'),
    path('who-we-are/vice-chancellor-message/', views.vice_chancellor_message, name='vice_chancellor_message'),
    path('who-we-are/university-organogram/', views.university_organogram, name='university_organogram'),
    path('leadership/', views.leadership, name='leadership'),
    path('leadership/pro-chancellor/', views.pro_chancellor, name='pro_chancellor'),
    path('leadership/pro-vice-chancellor-academics/', views.pro_vice_chancellor_academics, name='pro_vice_chancellor_academics'),
    path('leadership/executive-council/', views.executive_council, name='executive_council'),
    path('leadership/academic-council/', views.academic_council, name='academic_council'),
    path('leadership/governing-council/', views.governing_council, name='governing_council'),
    path('schools/', views.schools, name='schools'),
    path('faculty/', faculty, name='faculty'),
    path('admissions/', views.admissions, name='admissions'),
    path('research/phd-admissions/', views.phd_admissions, name='phd-admissions'),
    path('placements/', views.placements, name='placements'),
    path('student-life/', views.student_life, name='student_life'),
    path('student-life/student-clubs/', views.student_clubs, name='student_clubs'),
    path('student-life/infrastructure/', views.infrastructure, name='infrastructure'),
    path('student-life/infrastructure/<slug:slug>/', views.infrastructure_detail, name='infrastructure_detail'),
    path('student-life/library/', views.library, name='library'),
    path('student-life/library/<slug:slug>/', views.library_detail, name='library_detail'),
    path('student-life/hostels/', views.hostels, name='hostels'),
    path('student-life/hostels/<slug:slug>/', views.hostels_detail, name='hostels_detail'),
    path('student-life/transportation/', views.transportation, name='transportation'),
    path('student-life/transportation/<slug:slug>/', views.transportation_detail, name='transportation_detail'),

    path('student-life/sports/', views.sports, name='sports'),
    path('student-life/sports/<slug:slug>/', views.sports_detail, name='sports_detail'),
    path('student-life/virtual-tours/', views.virtual_tours, name='virtual_tours'),
    path('student-life/facilities/', views.facilities, name='facilities'),
    path('student-life/facilities/<slug:slug>/', views.facilities_detail, name='facilities_detail'),
    path('events/', views.events, name='events'),
    path('iqac/', views.iqac, name='iqac'),
    path('alumni/', views.alumni, name='alumni'),
    path('contact-us/', views.contact_us, name='contact_us'),

    path('agricultural-sciences/', views.school_agricultural_sciences, name='school_agricultural_sciences'),
    path('arts-natural-sciences/', views.school_arts_natural_sciences, name='school_arts_natural_sciences'),
    path('computational-intelligence/', views.school_computational_intelligence, name='school_computational_intelligence'),
    path('design/', views.school_design, name='school_design'),
    path('engineering-technology/', views.school_engineering_technology, name='school_engineering_technology'),
    path('entrepreneurship-management/', views.school_entrepreneurship_management, name='school_entrepreneurship_management'),
    path('law/', views.school_law, name='school_law'),
    path('life-health-sciences/', views.school_life_health_sciences, name='school_life_health_sciences'),
    path('nursing/', views.school_nursing, name='school_nursing'),
    path('pharmacy/', views.school_pharmacy, name='school_pharmacy'),
    
    # JU Documents URLs
    path('ju-documents/committees/', views.committees, name='committees'),
    path('ju-documents/statutes/', views.statutes, name='statutes'),
    path('ju-documents/ordinances/', views.ordinances, name='ordinances'),
    path('ju-documents/academic-regulations/', views.academic_regulations, name='academic_regulations'),
    path('ju-documents/examination-regulation/', views.examination_regulation, name='examination_regulation'),
    path('ju-documents/academic-calendar/', views.academic_calendar, name='academic_calendar'),
    path('ju-documents/leave-rules/', views.leave_rules, name='leave_rules'),
    path('ju-documents/ndli-member/', views.ndli_member, name='ndli_member'),
    path('ju-documents/ict-academy/', views.ict_academy, name='ict_academy'),
    path('ju-documents/newsletter/', views.newsletter, name='newsletter'),
    path('ju-documents/annual-report/', views.annual_report, name='annual_report'),
    path('ju-documents/mandatory-disclosure/', views.mandatory_disclosure, name='mandatory_disclosure'),
    path('ju-documents/downloads/', views.downloads, name='downloads'),
    path('ju-documents/admission-regulations/', views.admission_regulations, name='admission_regulations'),
    path('ju-documents/admission-flyer/', views.admission_flyer, name='admission_flyer'),
    path('ju-documents/aishe-code/', views.aishe_code, name='aishe_code'),
    path('ju-documents/annual-report-24-25/', views.annual_report_24_25, name='annual_report_24_25'),
    path('ju-documents/bci/', views.bci, name='bci'),
    path('ju-documents/disclaimer/', views.disclaimer, name='disclaimer'),
    path('ju-documents/hostel-policy/', views.hostel_policy, name='hostel_policy'),
    path('ju-documents/newsletter-24-25/', views.newsletter_24_25, name='newsletter_24_25'),
    path('ju-documents/pci/', views.pci, name='pci'),
    path('ju-documents/student-code-of-conduct/', views.student_code_of_conduct, name='student_code_of_conduct'),
    path('ju-documents/tn-gov-gaz-comm/', views.tn_gov_gaz_comm, name='tn_gov_gaz_comm'),
    path('ju-documents/tn-gov-gaz/', views.tn_gov_gaz, name='tn_gov_gaz'),
    path('ju-documents/tn-gov-ugc/', views.tn_gov_ugc, name='tn_gov_ugc'),
    path('ju-documents/tn-gov/', views.tn_gov, name='tn_gov'),
    path('ju-documents/tn-pu/', views.tn_pu, name='tn_pu'),
    path('ju-documents/tn-ugc/', views.tn_ugc, name='tn_ugc'),
    path('ju-documents/transportation-route/', views.transportation_route, name='transportation_route'),
    path('ju-documents/ugc/', views.ugc, name='ugc'),

    # Admissions URLs
    path('admissions/fee-structure/', views.fee_structure, name='fee_structure'),
    path('admissions/international/', views.international_admissions, name='international_admissions'),
    path('admissions/hostel-fee/', views.hostel_fee, name='hostel_fee'),
    path('admissions/transportation-fee/', views.transportation_fee, name='transportation_fee'),
    path('admissions/joy-scholarships/', views.ju_scholarships, name='ju_scholarships'),
    path('admissions/tn-government-scholarships/', views.tn_government_scholarships, name='tn_government_scholarships'),

    #Other Links
    path('other_links/achievements/', views.achievements, name='achievements'),
    path('other_links/visitors/', views.visitors, name='visitors'),
    path('other_links/press_and_media/', views.pressandmedia, name='press_and_media'),
    path('other_links/m-o-u/', views.m_o_u, name='m-o-u'),
    path('application-form/', views.application_form, name='application_form'),
    path('get-states/', views.get_states, name='get_states'),
    path('get-districts/', views.get_districts, name='get_districts'),
    path('get-cities/', views.get_cities, name='get_cities'),
    path('refresh-captcha/', views.refresh_captcha, name='refresh_captcha'),
    path('thank-you/', views.thank_you, name='thank_you'),
    path('login/', views.login_view, name='login'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('all_applications/', views.all_applications, name='all_applications'),
    path('forget-password/', views.forgot_password_view, name='forget_password'),
    path('otp-login/', views.otp_login_view, name='otp_login'),
    path('otp-verify/', views.otp_verify_view, name='otp_verify'),

    # Enrollment URLs
    path('enrollment/details/', views.details, name='details'),
    path('enrollment/declaration/', views.declaration, name='declaration'),
    path('enrollment/preview/', views.preview_view, name='preview'),
    path('enrollment/preview_pdf/', views.preview_pdf, name='preview_pdf'),
    path('enrollment/application-submitted/', views.application_submitted, name='application_submitted'),
    path('logout/', views.logout_view, name='logout'),
]
