# Generated by Django 5.1.1 on 2025-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
