# Generated by Django 5.1.1 on 2025-10-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
