# Generated by Django 5.1.1 on 2025-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_remove_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='faculty_photos/')),
                ('qualifications', models.TextField()),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
