# Generated by Django 5.1.1 on 2025-10-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('programmes_offered', models.TextField(blank=True)),
                ('programme_structure_eligibility', models.TextField(blank=True)),
                ('gallery', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('expected_graduate_attributes', models.TextField(blank=True)),
                ('new_targeted_skill_sets', models.TextField(blank=True)),
                ('philosophy', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('faculty_staff', models.TextField(blank=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='university.school')),
            ],
        ),
    ]
