# Generated by Django 5.1.1 on 2025-10-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_school_slug_schooldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
