# Generated by Django 5.1.1 on 2025-10-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_school_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('faculty_advisor', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
    ]
