# Generated by Django 5.1.1 on 2025-10-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_studentclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusTourRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('date_of_visit', models.DateField()),
                ('time_of_visit', models.TimeField()),
                ('no_of_people', models.PositiveIntegerField()),
                ('purpose_of_visit', models.TextField()),
                ('degree_interested', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
