# Generated by Django 5.1.1 on 2025-10-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_campustourregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('membership_in_council', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('membership_in_council', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GoverningCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('membership_in_council', models.TextField()),
            ],
        ),
    ]
