# Generated by Django 5.1.1 on 2025-10-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_academiccouncil_executivecouncil_governingcouncil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='infrastructure/')),
            ],
        ),
    ]
