# Generated by Django 5.1.1 on 2025-10-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
