# Generated by Django 5.1.1 on 2025-10-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_infrastructure_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='slug',
        ),
    ]
