# Generated by Django 5.1.1 on 2025-10-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_remove_infrastructure_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='gallery',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
