# Generated by Django 5.1.1 on 2025-10-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_infrastructure_gallery_infrastructure_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='gallery',
        ),
        migrations.CreateModel(
            name='InfrastructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='infrastructure/gallery/')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='university.infrastructure')),
            ],
        ),
    ]
