# Generated by Django 5.1.1 on 2025-10-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_studentgrievance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGrievance',
        ),
    ]
