# Generated by Django 4.2.25 on 2025-11-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_course_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country_code',
            field=models.CharField(default='+91', max_length=10),
        ),
    ]
