# Generated by Django 4.2.25 on 2025-11-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_application_password'),
        ('university', '0023_application_country_code'),
    ]

    operations = [
    ]
