# Generated by Django 4.2.25 on 2025-11-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0024_merge_20251104_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
