# Generated by Django 4.2.25 on 2025-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0026_alter_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
