# Generated by Django 4.2.25 on 2025-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0027_application_otp_code_application_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
