# Generated by Django 4.2.25 on 2025-11-07 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0028_application_application_number_application_declared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='declared',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitted',
        ),
        migrations.AddField(
            model_name='application',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.school'),
        ),
        migrations.CreateModel(
            name='PersonalAcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=50)),
                ('level_of_program', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('accommodation', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('aadhaar', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('matric_school', models.CharField(max_length=200)),
                ('matric_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('higher_secondary_school', models.CharField(max_length=200)),
                ('higher_secondary_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.application')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('agreed', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.application')),
            ],
        ),
    ]
