# Generated by Django 4.2.25 on 2025-11-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0029_remove_application_declared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.school'),
        ),
    ]
