# Generated by Django 4.2.25 on 2025-11-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0030_alter_application_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('initiated', 'Application Initiated'), ('completed', 'Application Completed'), ('enrolled', 'Enrolled')], default='initiated', max_length=20),
        ),
    ]
