# Generated by Django 4.2.25 on 2025-11-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0031_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalacademicdetails',
            name='application',
        ),
        migrations.DeleteModel(
            name='Declaration',
        ),
        migrations.DeleteModel(
            name='PersonalAcademicDetails',
        ),
    ]
