# Generated by Django 4.2.25 on 2025-11-10 05:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0032_remove_personalacademicdetails_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=512, null=True)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('program_level', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=120)),
                ('accommodation_status', models.CharField(choices=[('Day Scholar', 'Day Scholar'), ('Hosteller', 'Hosteller')], max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('aadhaar', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=120)),
                ('parent_mobile', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('x_school', models.CharField(max_length=160)),
                ('x_board', models.CharField(max_length=40)),
                ('x_state', models.CharField(max_length=60)),
                ('x_city', models.CharField(max_length=60)),
                ('x_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('x_after_qualification', models.CharField(max_length=20)),
                ('hs_school', models.CharField(max_length=160)),
                ('hs_state', models.CharField(max_length=60)),
                ('hs_city', models.CharField(max_length=60)),
                ('hs_board', models.CharField(max_length=40)),
                ('hs_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hs_result_status', models.CharField(max_length=20)),
                ('has_consultant_code', models.BooleanField(default=False)),
                ('consultant_code', models.CharField(blank=True, max_length=20)),
                ('declaration_agreed', models.BooleanField(default=False)),
                ('application_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='university.payment')),
            ],
        ),
    ]
