# Generated by Django 4.2.25 on 2025-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0033_payment_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('email', 'school')},
        ),
    ]
