# Generated by Django 4.2.25 on 2025-11-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0034_alter_application_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='razorpay_signature',
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
