# Generated by Django 4.2.25 on 2025-11-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0035_remove_application_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
