# Generated by Django 4.2.25 on 2025-11-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0036_alter_application_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
