# Generated by Django 4.2.25 on 2025-11-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0040_alter_application_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
