# Generated by Django 4.2.25 on 2025-11-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0041_alter_application_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
