# Generated by Django 4.2.25 on 2025-11-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0042_alter_application_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='payment',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='university.application'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
