# Generated by Django 4.2.25 on 2025-11-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0043_remove_enrollment_payment_enrollment_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='passport_country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='passport_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
