# Generated by Django 4.2.25 on 2025-11-12 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0044_enrollment_passport_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='diploma_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='diploma_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='diploma_university',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
