# Generated by Django 4.2.25 on 2025-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0045_enrollment_diploma_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='how_heard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
