# Generated by Django 4.2.25 on 2025-11-13 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0046_application_how_heard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='aadhaar',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar number must be exactly 12 digits.')]),
        ),
    ]
