# Generated by Django 4.2.25 on 2025-11-13 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0047_alter_enrollment_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='aadhaar',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Aadhaar number must be exactly 16 digits.')]),
        ),
    ]
