# Generated by Django 4.2.25 on 2025-11-13 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0048_alter_enrollment_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='aadhaar',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be 12 digits')]),
        ),
    ]
